サブエピソード削除ボタンを追加した
oonyaTeam/memory_share pull request #296
Opened 2021-10-18 00:12 UTC by 98zinkun

## 解決したIssue
- close #255

## 変更点
wrapper右下にサブエピソード削除ボタンを追加した
-

## スクリーンショッ
<img width="225" alt="スクリーンショット 2021-10-18 9 10 12" src="https://user-images.githubusercontent.com/85686526/137650111-6e8562f6-5dac-4e57-899d-9c723a55b2cf.png">
ト

2021-10-18 02:47 UTC, takumma requested changes
削除ボタンの表示非表示は別isssueを立ててるだけでも大丈夫です。
あと、多分subEpisodeWrapperを使ってる箇所が増えたと思うので一度変更をマージしてくるといいと思います

2021-10-18 02:47 UTC, takumma commented on lib/pages/sub_episode_page/sub_episode_page.dart
> +                                        Row(
このRowは不要かな

2021-10-18 02:47 UTC, takumma commented on lib/widgets/sub_episode_wrapper.dart
> +  const SubEpisodeWrapper(this.subEpisode, {required this.onPressed,Key? key}) : super(key: key);
削除を使わないところもあるので、ここはrequiredを消して使わないところではonPressedを指定しなくてもいいようにしてほしい

2021-10-18 02:47 UTC, takumma commented on lib/widgets/sub_episode_wrapper.dart
> +  final Function onPressed;
requiredを消すにあたって、指定しない場合はonPressedはnullになるので、Functionの後ろに?をつける必要があると思う

2021-10-18 02:47 UTC, takumma commented on lib/widgets/sub_episode_wrapper.dart
> +          Row(
ここでonPressedがヌルかどうかを判定して、削除ボタンの表示／非表示を切り替えてほしい

2021-10-19 11:31 UTC, takumma requested changes
修正お願いします（二度目ですまない

2021-10-19 11:31 UTC, takumma commented on lib/widgets/sub_episode_wrapper.dart
> +          Row(
`flag == 1` ってやるよりは、普通にbool値を受け取ってくるか、それか `(onPressed ==null) ? ` ってやる方がいいと思う

2021-10-19 11:31 UTC, takumma commented on lib/widgets/sub_episode_wrapper.dart
> +              Row(),
ここ消し忘れですか？

2021-10-19 11:58 UTC, 98zinkun commented on lib/widgets/sub_episode_wrapper.dart
> +              Row(),
yes

2021-10-19 12:00 UTC, 98zinkun commented on lib/widgets/sub_episode_wrapper.dart
> +              Row(),
いや、no。三項演算子使うのに必要かなって

2021-10-19 12:20 UTC, 98zinkun commented on lib/widgets/sub_episode_wrapper.dart
> +              Row(),
僕の理解が浅くてここでif文が使えなくて、三項演算子だったら使えたんだけど、何も表示させないっていうコードがわからなかったから空のRowをぶちこんでる

2021-10-19 12:34 UTC, 98zinkun commented on lib/widgets/sub_episode_wrapper.dart
> +              Row(),
(onPressed == null) ?　で判定とると、サブエピソード追加できなくなる。わけわからないです。

2021-10-19 12:38 UTC, 98zinkun commented on lib/widgets/sub_episode_wrapper.dart
> +              Row(),
fragで判定はダメですか？心折れたわ

2021-10-19 13:01 UTC, takumma approved these changes
OK

2021-10-19 13:01 UTC, merged